import { useMemo, useState } from 'react'
import PlasmaRing from './components/originkit/ui/plasma-ring'
import { applyDemoTransaction, demoFinancialState, formatINR } from './data/demoFinancialState'

type Transaction = { id: string; name: string; category: string; amount: number; date: string; type: 'Income' | 'Expense' | 'Transfer'; status: string; impact: string }
type Focus = 'overview' | 'transactions'
const categories = ['All', 'Food', 'Transport', 'Shopping', 'Education', 'Entertainment', 'Bills', 'Health', 'Travel', 'Salary', 'Other']
const recurring = [{ merchant: 'Internet Bill', amount: 899, frequency: 'Monthly', next: 'In 3 days' }, { merchant: 'Cloud Storage', amount: 149, frequency: 'Monthly', next: 'In 8 days' }, { merchant: 'Insurance', amount: 2800, frequency: 'Monthly', next: 'In 17 days' }, { merchant: 'Education', amount: 4500, frequency: 'Termly', next: 'Next month' }]

export default function MoneyIntelligence({ focus }: { focus: Focus }) {
  const [transactions, setTransactions] = useState<Transaction[]>(() => demoFinancialState.transactions.map((item, index) => ({ id: `demo-${index}`, ...item, category: item.category === 'Food & Dining' ? 'Food' : item.category, type: item.category === 'Income' ? 'Income' : 'Expense', status: 'Cleared', impact: item.category === 'Income' ? 'Positive' : 'Normal spending' })))
  const [search, setSearch] = useState('')
  const [typeFilter, setTypeFilter] = useState('All')
  const [categoryFilter, setCategoryFilter] = useState('All')
  const [sort, setSort] = useState('Newest')
  const [range, setRange] = useState('30D')
  const [selected, setSelected] = useState<Transaction | null>(null)
  const [modal, setModal] = useState<'add' | 'recurring' | null>(null)
  const [discretionary, setDiscretionary] = useState(0)
  const [addForm, setAddForm] = useState({ type: 'Expense', name: '', amount: 0, category: 'Food', date: '2026-08-27', notes: '' })
  const expenseTotal = demoFinancialState.monthlySpending
  const incomeTotal = demoFinancialState.income
  const safeToSpend = Math.max(0, demoFinancialState.safeToSpend - discretionary)
  const health = Math.max(0, demoFinancialState.financialHealth - Math.min(8, Math.floor(discretionary / 1500)))
  const filtered = useMemo(() => transactions.filter(item => item.name.toLowerCase().includes(search.toLowerCase()) && (typeFilter === 'All' || item.type === typeFilter || (typeFilter === 'Expenses' && item.type === 'Expense')) && (categoryFilter === 'All' || item.category === categoryFilter)).sort((a, b) => sort === 'Highest amount' ? b.amount - a.amount : sort === 'Lowest amount' ? a.amount - b.amount : sort === 'Oldest' ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date)), [transactions, search, typeFilter, categoryFilter, sort])
  const addTransaction = () => { if (!addForm.name || addForm.amount <= 0) return; const item: Transaction = { id: `${addForm.name}-${Date.now()}`, name: addForm.name, category: addForm.category, amount: addForm.amount, date: addForm.date, type: addForm.type as Transaction['type'], status: 'Added locally', impact: addForm.type === 'Income' ? 'Positive' : addForm.amount > demoFinancialState.safeToSpend ? 'Potential overspend' : 'Normal spending' }; applyDemoTransaction(item.type, item.amount); setTransactions(previous => [item, ...previous]); setAddForm({ type: 'Expense', name: '', amount: 0, category: 'Food', date: '2026-08-27', notes: '' }); setModal(null) }
  const removeTransaction = (id: string) => { const item = transactions.find(transaction => transaction.id === id); if (!item) return; applyDemoTransaction(item.type, -item.amount); setTransactions(previous => previous.filter(transaction => transaction.id !== id)) }
  return <div className="workspace-page money-page"><div className="page-intro"><div><span className="eyebrow">{focus === 'overview' ? 'MONEY / INTELLIGENCE LAYER' : 'TRANSACTIONS / SIGNAL CENTER'}</span><h1>{focus === 'overview' ? <>Your Money.<br /><em>Every signal matters.</em></> : <>Transaction<br /><em>signal center.</em></>}</h1><p>{focus === 'overview' ? 'Every transaction becomes a signal. FINOVA turns movement into context, using clearly labeled demo financial data.' : 'Search, filter, and inspect simulated transactions in one focused workspace.'}</p></div><span className="demo-badge">DEMO FINANCIAL DATA</span></div><MoneySnapshot expenseTotal={expenseTotal} incomeTotal={incomeTotal} safeToSpend={safeToSpend} health={health} /><div className="money-toolbar"><div className="money-tabs"><button className={focus === 'overview' ? 'active' : ''} onClick={() => dispatchNav('Money')}>Money overview</button><button className={focus === 'transactions' ? 'active' : ''} onClick={() => dispatchNav('Transactions')}>Transactions</button></div><button className="add-transaction" onClick={() => setModal('add')}>＋ Add Transaction</button></div>{focus === 'overview' ? <><div className="money-main-grid"><SpendingAnalytics range={range} setRange={setRange} transactions={transactions} /><SafeSpend value={safeToSpend} discretionary={discretionary} setDiscretionary={setDiscretionary} /></div><div className="money-lower-grid"><CategoryIntelligence transactions={transactions} filter={categoryFilter} setFilter={setCategoryFilter} /><RecurringSignals open={() => setModal('recurring')} /></div><Signals /></> : <><TransactionControls search={search} setSearch={setSearch} typeFilter={typeFilter} setTypeFilter={setTypeFilter} categoryFilter={categoryFilter} setCategoryFilter={setCategoryFilter} sort={sort} setSort={setSort} /><TransactionTimeline transactions={filtered} select={setSelected} remove={removeTransaction} /></>}{selected && <TransactionDetail item={selected} close={() => setSelected(null)} />}{modal === 'add' && <AddTransaction form={addForm} setForm={setAddForm} submit={addTransaction} close={() => setModal(null)} />}{modal === 'recurring' && <SimpleModal title="Recurring signal management" text="Recurring transaction management will be connected to live user data in a later integration stage." close={() => setModal(null)} />}</div>
}

function dispatchNav(view: string) { window.dispatchEvent(new CustomEvent('finova-navigate', { detail: view })) }
function MoneySnapshot({ expenseTotal, incomeTotal, safeToSpend, health }: { expenseTotal: number; incomeTotal: number; safeToSpend: number; health: number }) { const addedIncome = incomeTotal - demoFinancialState.income; const addedExpenses = expenseTotal - demoFinancialState.monthlySpending; const items = [['CURRENT BALANCE', formatINR(demoFinancialState.balance + addedIncome - addedExpenses)], ['MONTHLY INCOME', formatINR(incomeTotal)], ['MONTHLY SPENDING', formatINR(expenseTotal)], ['SAFE-TO-SPEND', formatINR(safeToSpend)], ['FINANCIAL HEALTH', `${health} / 100`]]; return <div className="money-snapshot">{items.map(([label, value]) => <div key={label}><span>{label}<i>DEMO</i></span><strong>{value}</strong><small>Illustrative signal</small></div>)}</div> }
function SpendingAnalytics({ range, setRange, transactions }: { range: string; setRange: (value: string) => void; transactions: Transaction[] }) { const bars = range === '7D' ? [30, 46, 34, 58, 43, 62, 48] : range === '90D' ? [38, 52, 46, 68, 55, 61, 50, 72, 59] : [48, 61, 52, 68, 57, 73]; return <section className="spending-analytics"><div className="card-top"><div><span className="panel-kicker">SPENDING ANALYTICS <i className="demo-dot" /> DEMO DATA</span><h2>Movement over time</h2></div><div className="range-tabs">{['7D', '30D', '90D'].map(item => <button className={range === item ? 'active' : ''} onClick={() => setRange(item)} key={item}>{item}</button>)}</div></div><div className="analytics-chart">{bars.map((height, index) => <div className="analytics-bar" key={index}><i style={{ height: `${height}%` }} title={`Demo spending signal ${index + 1}`} /><span>{index + 1}</span></div>)}</div><div className="analytics-legend"><span><i /> Spending</span><span><i /> Income</span><small>{transactions.length} demo signals observed</small></div></section> }
function SafeSpend({ value, discretionary, setDiscretionary }: { value: number; discretionary: number; setDiscretionary: (value: number) => void }) { return <section className="safe-spend-engine"><div className="safe-core"><PlasmaRing background="rgba(0,0,0,0)" colors={['#73eaff', '#6677ff', '#b55dff']} density={34} speed={25} centerOpacity={8} scale={30} style={{ width: '100%', height: '100%' }} /><span>SAFE<br /><small>DEMO ENGINE</small></span></div><span className="panel-kicker">SAFE-TO-SPEND / FINOVA SIMULATION</span><h2>{formatINR(value)}</h2><p>Available after demo commitments and current spending.</p><label>Adjust discretionary spending<output>+ {formatINR(discretionary)}</output><input aria-label="Adjust discretionary spending" type="range" min="0" max="10000" step="500" value={discretionary} onChange={event => setDiscretionary(Number(event.target.value))} /></label><strong className={value > 10000 ? 'safe-state' : value > 4000 ? 'caution-state' : 'avoid-state'}>{value > 10000 ? 'SAFE' : value > 4000 ? 'CONSIDER' : 'AVOID'}</strong></section> }
function CategoryIntelligence({ transactions, filter, setFilter }: { transactions: Transaction[]; filter: string; setFilter: (value: string) => void }) { const names = ['Food', 'Transport', 'Shopping', 'Education', 'Bills', 'Travel']; const total = transactions.filter(item => item.type === 'Expense').reduce((sum, item) => sum + item.amount, 0) || 1; return <section className="category-intelligence"><div className="card-top"><div><span className="panel-kicker">CATEGORY INTELLIGENCE</span><h2>Where signals collect</h2></div></div><div className="category-list">{names.map(name => { const amount = transactions.filter(item => item.category === name).reduce((sum, item) => sum + item.amount, 0); return <button className={filter === name ? 'active' : ''} key={name} onClick={() => setFilter(filter === name ? 'All' : name)}><span>{name}</span><strong>{formatINR(amount)}</strong><small>{Math.round(amount / total * 100)}% of demo spending · {amount > 4000 ? '+12%' : '−4%'}</small><i><b style={{ width: `${Math.min(100, amount / total * 100)}%` }} /></i></button> })}</div></section> }
function RecurringSignals({ open }: { open: () => void }) { return <section className="recurring-signals"><div className="card-top"><div><span className="panel-kicker">RECURRING SIGNALS <i className="demo-dot" /> SIMULATED</span><h2>Expected patterns</h2></div></div>{recurring.map(item => <div className="recurring-row" key={item.merchant}><div><strong>{item.merchant}</strong><small>{item.frequency} · next {item.next}</small></div><b>{formatINR(item.amount)}</b><button onClick={open}>Manage</button></div>)}</section> }
function Signals() { return <section className="money-signals"><div className="card-top"><div><span className="panel-kicker">FINOVA SIGNALS</span><h2>What the pattern suggests</h2></div></div><div className="signal-grid"><button onClick={() => dispatchNav('Smart Purchases')}><span>SHOPPING PATTERN</span><p>Shopping is higher than its usual demo pattern. Compare the next purchase before committing.</p><b>Open Smart Purchases ↗</b></button><button onClick={() => dispatchNav('Financial Twin')}><span>FINANCIAL TWIN</span><p>Your demo signals are being organized into a clearer view of cash flow and goals.</p><b>View Financial Twin ↗</b></button><button onClick={() => dispatchNav('AI Advisor')}><span>ASK FINOVA</span><p>Ask how current spending may affect the Travel Goal in the illustrative model.</p><b>Open AI Advisor ↗</b></button></div></section> }
function TransactionControls({ search, setSearch, typeFilter, setTypeFilter, categoryFilter, setCategoryFilter, sort, setSort }: { search: string; setSearch: (value: string) => void; typeFilter: string; setTypeFilter: (value: string) => void; categoryFilter: string; setCategoryFilter: (value: string) => void; sort: string; setSort: (value: string) => void }) { return <div className="transaction-controls"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search transactions" aria-label="Search transactions" /><select value={typeFilter} onChange={event => setTypeFilter(event.target.value)}><option>All</option><option>Income</option><option>Expenses</option><option>Transfer</option></select><select value={categoryFilter} onChange={event => setCategoryFilter(event.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select><select value={sort} onChange={event => setSort(event.target.value)}><option>Newest</option><option>Oldest</option><option>Highest amount</option><option>Lowest amount</option></select></div> }
function TransactionTimeline({ transactions, select, remove }: { transactions: Transaction[]; select: (item: Transaction) => void; remove: (id: string) => void }) { return <section className="transaction-timeline"><div className="timeline-header"><span>TRANSACTION TIMELINE</span><small>{transactions.length} demo results</small></div>{transactions.map(item => <article key={item.id} onClick={() => select(item)}><span className="timeline-date">{item.date}</span><div className="timeline-dot" /><div className="timeline-detail"><strong>{item.name}</strong><small>{item.category} · {item.type} · {item.status}</small></div><b className={item.type === 'Income' ? 'income-text' : ''}>{item.type === 'Income' ? '+' : '−'} {formatINR(item.amount)}</b><button aria-label={`Remove ${item.name}`} onClick={event => { event.stopPropagation(); remove(item.id) }}>×</button></article>)}</section> }
function TransactionDetail({ item, close }: { item: Transaction; close: () => void }) { return <aside className="transaction-detail"><button onClick={close} aria-label="Close transaction detail">×</button><span className="panel-kicker">SIMULATED AI INSIGHT</span><h2>{item.name}</h2><strong>{formatINR(item.amount)}</strong><div><span>Category</span><b>{item.category}</b></div><div><span>Date</span><b>{item.date}</b></div><div><span>Type</span><b>{item.type}</b></div><div className="signal-result"><span>FINOVA SIGNAL</span><b>{item.impact}</b><p>FINOVA noticed this because it is part of the current illustrative transaction pattern.</p></div></aside> }
function AddTransaction({ form, setForm, submit, close }: { form: { type: string; name: string; amount: number; category: string; date: string; notes: string }; setForm: (form: { type: string; name: string; amount: number; category: string; date: string; notes: string }) => void; submit: () => void; close: () => void }) { return <div className="modal-backdrop" onClick={close}><section className="modal transaction-modal" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close add transaction">×</button><span className="panel-kicker">ADD TRANSACTION / DEMO DATA</span><h2>Add a new signal.</h2><label>Transaction type<select value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}><option>Expense</option><option>Income</option><option>Transfer</option></select></label><label>Merchant<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Merchant or source" /></label><label>Amount<input type="number" min="0" value={form.amount || ''} onChange={event => setForm({ ...form, amount: Number(event.target.value) })} placeholder="0" /></label><label>Category<select value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}>{categories.slice(1).map(item => <option key={item}>{item}</option>)}</select></label><label>Date<input type="date" value={form.date} onChange={event => setForm({ ...form, date: event.target.value })} /></label><label>Notes<input value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} placeholder="Optional note" /></label><div className="modal-actions"><button onClick={close}>Cancel</button><button className="soft-button" onClick={submit}>Add Transaction ↗</button></div></section></div> }
function SimpleModal({ title, text, close }: { title: string; text: string; close: () => void }) { return <div className="modal-backdrop" onClick={close}><section className="modal" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close modal">×</button><span className="panel-kicker">FINOVA / DEMO</span><h2>{title}</h2><p>{text}</p><button className="soft-button" onClick={close}>Close ↗</button></section></div> }
