import { useMemo, useState } from 'react'
import PlasmaRing from './components/originkit/ui/plasma-ring'
import PulsatingBorder from './components/originkit/ui/pulsating-border-custom-style'
import { demoFinancialState, formatINR } from './data/demoFinancialState'

const categories = ['Electronics', 'Education', 'Travel', 'Fashion', 'Home', 'Fitness', 'Entertainment', 'Other']
const occasions = ['Birthday', 'Anniversary', 'Graduation', 'Wedding', 'Festival', 'Thank You', 'Other']
const giftStyles = ['Useful', 'Emotional', 'Premium', 'Fun', 'Personalized']
const baseOptions = [
  { name: 'Current plan', price: 12000 },
  { name: 'Lower-cost option', price: 8000 },
  { name: 'Premium option', price: 28000 },
]

type Status = 'SAFE' | 'CONSIDER' | 'AVOID'

export default function SmartPurchases() {
  const [purchase, setPurchase] = useState('Laptop for college')
  const [category, setCategory] = useState('Electronics')
  const [price, setPrice] = useState(20000)
  const [purchaseDate, setPurchaseDate] = useState('2026-09-15')
  const [priority, setPriority] = useState('Medium')
  const [installment, setInstallment] = useState(0)
  const [purpose, setPurpose] = useState('Planned purchase')
  const [analysisAction, setAnalysisAction] = useState('')
  const [giftOccasion, setGiftOccasion] = useState('Birthday')
  const [giftRecipient, setGiftRecipient] = useState('A close friend')
  const [giftInterest, setGiftInterest] = useState('Gaming')
  const [giftBudget, setGiftBudget] = useState(3000)
  const [giftStyle, setGiftStyle] = useState('Useful')
  const [comparison, setComparison] = useState(0)
  const [eventOpen, setEventOpen] = useState(false)
  const [eventAmount, setEventAmount] = useState(8000)
  const [eventType, setEventType] = useState('Emergency / Event')

  const purchaseImpact = useMemo(() => calculateImpact(price, installment, purchaseDate), [price, installment, purchaseDate])
  const gift = useMemo(() => calculateGift(giftBudget, giftStyle, giftInterest), [giftBudget, giftStyle, giftInterest])
  const selectedOption = baseOptions[comparison]
  const eventStatus = statusFor(eventAmount)

  return <div className="workspace-page smart-purchases-page">
    <div className="page-intro"><div><span className="eyebrow">SMART PURCHASES / DECISION LAYER</span><h1>Smart Purchases<br /><em>for real life.</em></h1><p>Make purchases that fit your financial reality. FINOVA AI SIMULATION uses demo state calculations only.</p></div><span className="demo-badge">DEMO / SIMULATION DATA</span></div>
    <div className="purchase-intelligence"><Stat label="AVAILABLE TO SPEND" value={formatINR(purchaseImpact.remainingSafe)} /><Stat label="MONTHLY SPENDING" value={formatINR(demoFinancialState.monthlySpending)} /><Stat label="UPCOMING COMMITMENTS" value={formatINR(demoFinancialState.upcoming.reduce((sum, item) => sum + item.amount, 0))} /><Stat label="FINANCIAL HEALTH IMPACT" value={purchaseImpact.healthImpact} /></div>
    <div className="purchase-planner-layout"><PulsatingBorder colors={['#61eaff', '#716dff', '#61eaff']} radius={2} thickness={3} intensity={22} bloom={30} style={{ display: 'block' }}><section className="purchase-planner"><div className="card-top"><div><span className="panel-kicker">PURCHASE PLANNER</span><h2>Make the decision visible.</h2></div><span className="simulation-tag">FINOVA AI SIMULATION</span></div><div className="planner-fields"><label>What are you buying?<input value={purchase} onChange={event => setPurchase(event.target.value)} /></label><label>Category<select value={category} onChange={event => setCategory(event.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select></label><label>Price<output>{formatINR(price)}</output><input type="range" min="1000" max="100000" step="1000" value={price} onChange={event => setPrice(Number(event.target.value))} /></label><label>Desired purchase date<input type="date" value={purchaseDate} onChange={event => setPurchaseDate(event.target.value)} /></label><label>Priority<select value={priority} onChange={event => setPriority(event.target.value)}><option>High</option><option>Medium</option><option>Low</option></select></label><label>Monthly installment<output>{installment ? formatINR(installment) : 'None'}</output><input type="range" min="0" max="20000" step="500" value={installment} onChange={event => setInstallment(Number(event.target.value))} /></label><label>Purpose<input value={purpose} onChange={event => setPurpose(event.target.value)} /></label></div><div className="planner-results"><Metric label="SAFE-TO-SPEND IMPACT" value={`− ${formatINR(purchaseImpact.safeImpact)}`} /><Metric label="GOAL IMPACT" value={purchaseImpact.goalImpact} /><Metric label="CASH-FLOW IMPACT" value={formatINR(purchaseImpact.cashImpact)} /><Metric label="PURCHASE PRESSURE" value={`${purchaseImpact.pressure}%`} /></div><div className="recommendation-row"><div><span>SIMULATION STATUS</span><strong className={purchaseImpact.status.toLowerCase()}>{purchaseImpact.status}</strong><p>{purchaseImpact.explanation}</p></div><span className="priority-mark">{priority} priority</span></div></section></PulsatingBorder><PurchaseImpact price={price} purchase={purchase} status={purchaseImpact.status} selectedOption={selectedOption.name} /></div>
    <section className="analysis-panel"><div><span className="panel-kicker">SIMULATED AI ANALYSIS / DEMO DATA</span><h2>Context before commitment.</h2><p>Based on your current demo financial state, this purchase appears {purchaseImpact.status === 'SAFE' ? 'manageable' : 'worth reviewing'} and may affect your comfortable spending range.</p><div className="analysis-reasons"><span>WHY THIS RESULT</span><b>Available safe-to-spend range</b><b>Monthly cash-flow capacity</b><b>Upcoming commitments</b><b>Goal protection context</b></div></div><div className="analysis-metrics"><Metric label="SAFE-TO-SPEND IMPACT" value={formatINR(purchaseImpact.remainingSafe)} /><Metric label="GOAL IMPACT" value={purchaseImpact.goalImpact} /><Metric label="CONFIDENCE" value="Demo logic" /><div className="analysis-actions">{['Buy now', 'Wait 2 weeks', 'Reduce budget', 'Compare alternatives'].map(action => <button className={analysisAction === action ? 'selected' : ''} onClick={() => setAnalysisAction(action)} key={action}>{action} <span>↗</span></button>)}</div>{analysisAction && <p className="action-feedback">Selected demo action: <strong>{analysisAction}</strong>. No transaction has been created.</p>}</div></section>
    <GiftAdvisor occasion={giftOccasion} setOccasion={setGiftOccasion} recipient={giftRecipient} setRecipient={setGiftRecipient} interest={giftInterest} setInterest={setGiftInterest} budget={giftBudget} setBudget={setGiftBudget} style={giftStyle} setStyle={setGiftStyle} gift={gift} />
    <section className="comparison-section"><div className="card-top"><div><span className="panel-kicker">PURCHASE COMPARISON / DEMO</span><h2>Choose with context.</h2></div><span className="simulation-tag">UP TO 3 OPTIONS</span></div><div className="comparison-table"><div className="comparison-head"><span>OPTION</span><span>PRICE</span><span>BUDGET FIT</span><span>GOAL IMPACT</span><span>STATUS</span></div>{baseOptions.map((option, index) => <button className={comparison === index ? 'selected' : ''} onClick={() => setComparison(index)} key={option.name}><span>{option.name}</span><b>{formatINR(option.price)}</b><span>{option.price <= demoFinancialState.safeToSpend ? 'Within range' : 'Stretch'}</span><span>{option.price > 15000 ? '+ 9 days' : 'Minimal'}</span><strong>{statusFor(option.price)}</strong></button>)}</div><p className="comparison-note">Selected: {selectedOption.name} · monthly impact is estimated locally from demo data.</p></section>
    <section className="gift-budget-section"><div><span className="panel-kicker">GIFT BUDGET INTELLIGENCE</span><h2>Thoughtful, not careless.</h2><p>Compare a gift budget with an illustrative comfortable range before you search.</p></div><div className="budget-meter"><div><span>₹0</span><span>{formatINR(demoFinancialState.safeToSpend)}</span></div><i className={giftBudget > 5000 ? 'stretch' : giftBudget > 3000 ? 'balanced' : ''}><b style={{ width: `${Math.min(100, giftBudget / 10000 * 100)}%` }} /></i><strong>{giftBudget <= 2500 ? 'COMFORTABLE' : giftBudget <= 5000 ? 'BALANCED' : giftBudget <= 8000 ? 'STRETCH' : 'NOT RECOMMENDED'}</strong></div></section>
    <section className="event-mode-action"><div><span className="panel-kicker">SUDDEN EXPENSE / EVENT MODE</span><h2>Unexpected Expense?</h2><p>Model an urgent event against your current demo context before acting.</p></div><button onClick={() => setEventOpen(true)}>Open Event Mode ↗</button></section>
    {eventOpen && <EventModal type={eventType} amount={eventAmount} setType={setEventType} setAmount={setEventAmount} status={eventStatus} close={() => setEventOpen(false)} />}
  </div>
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="purchase-stat"><span>{label}<i>DEMO</i></span><strong>{value}</strong><small>Illustrative calculation</small></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="purchase-metric"><span>{label}</span><strong>{value}</strong></div> }
function calculateImpact(price: number, installment: number, date: string) { const delay = Math.max(0, Math.ceil(price / 5000) - 2 + (date > '2026-10-01' ? -1 : 0)); const safeImpact = Math.min(demoFinancialState.safeToSpend, Math.round(price * .72)); const remainingSafe = Math.max(0, demoFinancialState.safeToSpend - safeImpact); const cashImpact = installment || Math.round(price / 3); const status = statusFor(price); return { delay, safeImpact, remainingSafe, cashImpact, pressure: Math.min(100, Math.round(price / demoFinancialState.balance * 100)), status, goalImpact: delay ? `+ ${delay} days` : 'Minimal', healthImpact: status === 'SAFE' ? 'No change' : status === 'CONSIDER' ? '− 2 pts' : '− 5 pts', explanation: status === 'SAFE' ? 'Within the illustrative comfortable spending range.' : status === 'CONSIDER' ? 'This purchase may reduce spending room and shift a demo goal.' : 'This amount is high relative to the demo state. Consider alternatives.' } }
function statusFor(price: number): Status { return price <= demoFinancialState.safeToSpend ? 'SAFE' : price <= demoFinancialState.balance * .25 ? 'CONSIDER' : 'AVOID' }
function PurchaseImpact({ price, purchase, status, selectedOption }: { price: number; purchase: string; status: Status; selectedOption: string }) { return <section className="purchase-impact"><div className="impact-visual"><div className="impact-orbit orbit-a" /><div className="impact-orbit orbit-b" /><div className="impact-core"><PlasmaRing background="rgba(0,0,0,0)" colors={['#73eaff', '#6677ff', '#b55dff']} density={40} speed={24} centerOpacity={8} scale={30} style={{ width: '100%', height: '100%' }} /><span>₹{Math.round(price / 1000)}k<small>PURCHASE</small></span></div><span className="impact-label impact-label-one">CURRENT STATE</span><span className="impact-label impact-label-two">SHORT-TERM IMPACT</span><span className="impact-label impact-label-three">GOAL IMPACT</span><span className="impact-label impact-label-four">FUTURE PROJECTION</span></div><div className="impact-copy"><span className="panel-kicker">PURCHASE IMPACT / DEMO MODEL</span><h2>{purchase || 'Your purchase'}<br /><em>in context.</em></h2><div className="impact-path">CURRENT FINANCIAL STATE <b>↓</b> PURCHASE <b>↓</b> GOAL PROJECTION</div><strong className={`impact-status ${status.toLowerCase()}`}>{status} · {selectedOption}</strong><p>Every impact shown is calculated from the current illustrative state. Nothing is purchased or saved.</p></div></section> }
function GiftAdvisor({ occasion, setOccasion, recipient, setRecipient, interest, setInterest, budget, setBudget, style, setStyle, gift }: { occasion: string; setOccasion: (value: string) => void; recipient: string; setRecipient: (value: string) => void; interest: string; setInterest: (value: string) => void; budget: number; setBudget: (value: number) => void; style: string; setStyle: (value: string) => void; gift: { range: string; status: string; concepts: string[] } }) { return <section className="gift-advisor-section"><div className="gift-advisor-copy"><span className="panel-kicker">GIFT ADVISOR / DEMO DATA</span><h2>Find a thoughtful gift<br /><em>without losing control.</em></h2><p>Describe the moment. FINOVA creates illustrative gift concepts, not live product results.</p><div className="gift-fields"><label>Occasion<select value={occasion} onChange={event => setOccasion(event.target.value)}>{occasions.map(item => <option key={item}>{item}</option>)}</select></label><label>Recipient<input value={recipient} onChange={event => setRecipient(event.target.value)} /></label><label>Interests<input value={interest} onChange={event => setInterest(event.target.value)} /></label><label>Preferred style<select value={style} onChange={event => setStyle(event.target.value)}>{giftStyles.map(item => <option key={item}>{item}</option>)}</select></label><label>Budget<output>{formatINR(budget)}</output><input type="range" min="500" max="15000" step="500" value={budget} onChange={event => setBudget(Number(event.target.value))} /></label></div></div><div className="gift-results"><span className="simulation-tag">FINOVA RECOMMENDATION / ILLUSTRATIVE</span><h3>Recommended range <strong>{gift.range}</strong></h3><strong className="gift-status">{gift.status}</strong>{gift.concepts.map(concept => <div className="gift-concept" key={concept}><span>DEMO CONCEPT</span><b>{concept}</b><small>Budget fit · {gift.status.toLowerCase()} · Goal impact calculated locally</small></div>)}<button className="soft-button" onClick={() => alert('Live product search will be connected in a future integration.')}>Find Actual Products ↗</button></div></section> }
function calculateGift(budget: number, style: string, interest: string) { return { range: `${formatINR(Math.max(1000, Math.round(budget * .6)))} – ${formatINR(budget)}`, status: budget <= 3000 ? 'COMFORTABLE' : budget <= 6000 ? 'BALANCED' : 'STRETCH', concepts: [`${style} ${interest} accessory`, `Personalized ${interest} keepsake`, `Curated ${interest} bundle`] } }
function EventModal({ type, amount, setType, setAmount, status, close }: { type: string; amount: number; setType: (value: string) => void; setAmount: (value: number) => void; status: Status; close: () => void }) { return <div className="modal-backdrop" onClick={close}><section className="modal event-modal" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close event mode">×</button><span className="panel-kicker">EVENT MODE / DEMO CALCULATION</span><h2>Life does not follow your budget.</h2><label>What happened?<select value={type} onChange={event => setType(event.target.value)}><option>Emergency / Event</option><option>Birthday</option><option>Travel</option><option>Repair</option><option>Family event</option></select></label><label>Expected amount<output>{formatINR(amount)}</output><input type="range" min="1000" max="50000" step="1000" value={amount} onChange={event => setAmount(Number(event.target.value))} /></label><label>When is it needed?<input type="date" defaultValue="2026-09-01" /></label><div className="event-result"><Metric label="AVAILABLE EVENT BUDGET" value={formatINR(demoFinancialState.safeToSpend)} /><Metric label="GOAL IMPACT" value={amount > 15000 ? '+ 9 days' : 'Minimal'} /><Metric label="RISK LEVEL" value={status} /></div><button className="soft-button" onClick={close}>Review later ↗</button></section></div> }
